stages:
  - build

before_script:
  - test -f Miniconda3-latest-Linux-x86_64.sh || wget -nv https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b -p `pwd`/local_env
  - export PATH=`pwd`/local_env/bin:$PATH
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

build:
  stage: build
  tags:
    - ncrc4
  script:
    - conda env create --file repro.yml
    - . activate repro
    - conda list -e
    - python create_grids.py
    - md5sum -c checksums.txt

